### ISSUE TITLE
AAU, I connect with my account

### ISSUE THREAD

**Issue by alainncls** [MetaMask/permissionless-snaps-directory#1]
As a user,
I want to connect with my account,
So that I can use the platform

----

## Technical notes:
* Use [ConnectKit button](https://docs.family.co/connectkit)
* [Customize the button](https://docs.family.co/connectkit/theming)

## Out of scope:
* Interaction on the connect button after the connection is done (cf. #13)

## Acceptance Criteria:
- [x] Given that I click on the connect button, the connection modal appears with the "MetaMask" option,
- [x] Given that I click on the "MetaMask" option, the "MetaMask" popup appears and I can accept the connection to the dApp,
- [x] Given that I accepted the connection, the header displays my connected account information.

## Definition of Ready
- [X] Figma design ready
- [X] Acceptance criteria ready
- [X] Technical grooming done
- [x] Product team has validated the use of ConnectKit from Family (competitor wallet)

## Mockup design

=> [FIGMA](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=1464%3A61172&mode=design&t=LOjPj9J00CsEAjPK-1)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1lHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1add71f8dfd842d5b00b9a728c1a29a9bc278855/connect-wallet.png)

**Comment by dayksx** [comment]
@Montoya is validating that we can use ConnectKit from Family (competitor sdk) for Snaps Directory and then move to MetaMask SDK when we will have a native integration with wagmi

**Comment by vivek-consensys** [comment]
Tested full acceptance criteria, see here: 
https://www.notion.so/metamask-consensys/04b33da3b17f42619427cddb7a806746?v=112946b65bc844b6a4a2bddd321488ea
