### ISSUE TITLE
AAU I see snaps community sentiment as "Not enough reviews" by default

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#103]
As a User,
I see snaps sentiment as "Not enough reviews" by default

---

## Technical notes:

-
Note : as per discussion earlier, it is decided to use Insufficient reviews instead of Not enough reviews

## Out of scope:

-
-

## Acceptance Criteria:

- [ ] Given that I am in snap profile without any review yet, I see the community sentiment "Not enought reviews"

## Definition of Ready

- [ ] Figma design ready
- [ ] Acceptance criteria ready
- [ ] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com)

**Comment by satyajeetkolhapure** [comment]
Note : as per discussion earlier, it is decided to use Insufficient reviews instead of Not enough reviews

**Comment by jvelasquez** [comment]
Checked in dev, This can be moved to done: 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0xvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e576c90ffb644eca764f31bc6f54f0521e4ba58/image.png" alt="image.png" />
