### ISSUE TITLE
AAU, I access the Snaps Directory with the domain permissionless.snaps.metamask.io

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#104]
As a XXX,
I want to ...,
So that ...

---

## Technical notes:

-
-

## Out of scope:

-
-

## Acceptance Criteria:

- [ ] Given that ... , when ..., then ...
- [ ] Given that ... , when ..., then ...

## Definition of Ready

- [ ] Figma design ready
- [ ] Acceptance criteria ready
- [ ] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com)

**Comment by stanleyyconsensys** [comment]
still pending from OPS team

**Comment by stanleyyconsensys** [comment]
PR: https://github.com/Consensys/metamask-cloudflare-infra/pull/31

still await for merge
