### ISSUE TITLE
AAU, my cursor should be a pointer when hovering the community sentiment badge on a snap page

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#105]
As a XXX,
I want to ...,
So that ...

---

## Technical notes:

-
-

## Out of scope:

-
-

## Acceptance Criteria:

- [ ] Given that ... , when ..., then ...
- [ ] Given that ... , when ..., then ...

## Definition of Ready

- [ ] Figma design ready
- [ ] Acceptance criteria ready
- [ ] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com)

<img width="215" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1Z5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--793d2719c62f2a627beff72e45a05ed7c159c4ad/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
Validated in https://permissionless.snaps.metamask.io/snap/npm/mystery-fox/ 

<img width="1333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG5uQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbe11e1a3522e78b4d5bde4f2b4ce6faacf62c1b/Screenshot%202024-05-16%20at%2012.18.59.png" alt="Screenshot 2024-05-16 at 12.18.59.png" />

**Comment by jvelasquez** [comment]
Validated in https://permissionless.snaps.metamask.io/snap/npm/mystery-fox/ 

<img width="1333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG5uQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbe11e1a3522e78b4d5bde4f2b4ce6faacf62c1b/Screenshot%202024-05-16%20at%2012.18.59.png" alt="Screenshot 2024-05-16 at 12.18.59.png" />

**Comment by jvelasquez** [comment]
@satyajeetkolhapure  put this into the DONE column please, I lack permissions

**Comment by jvelasquez** [comment]
Checked on DEV too, it has been implemented: 
<img width="1327" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3pvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5a6335914f7eb86cf1bb18d98b0edf129c99002/Screenshot%202024-05-16%20at%2015.28.05.png" alt="Screenshot 2024-05-16 at 15.28.05.png" />
