### ISSUE TITLE
AAU, I see the detailed information of endorsements & reports for a specific snap.

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#113]
As a User,
 I see the detailed information of endorsements & reports for a specific snap.
So that I can transparently see the incoming data and make my own opinion regarding the community sentiment

---

## Technical notes:
- Fetch all the endorsements & disputes for a specific Snap (subject)
- First 100

## Out of scope:
- No pagination

## Acceptance Criteria:

- [ ] Given that I navigate to a Snap profile that have (1 to many) endorsement and/or report I see the "Activity" section with the issued endorsements & reports for this Snap
- [ ] Given that I navigate to a Snap profile that have doesn't have endorsement/report, I don't see the "Activity" section
- [ ] Given that I click to the issuer link I access the the user's profile

## Definition of Ready

- [ ] Figma design ready
- [x] Acceptance criteria ready
- [ ] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com)

Activity
<img width="1152" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3o5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a65b2cb82672838fd4874f6b88a5633d261855a/image.png" alt="image.png" />

Overview
<img width="526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1QrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b58106cdd1c7afaf61471ecceef132cf55bd8595/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
@alainncls , @satyajeetkolhapure @ChaimaKhiari  is the "Community Sentiment" supposed to overrule the "Endorsements" section in the SNAP details?

https://permissionless.snaps.metamask.io/dev/snap/npm/solflare-wallet/solana-snap/ 

<img width="1279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy8wQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c00b6fbd9c0f1b173caf3376e1571b417f785c60/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
At first, the idea was to display starts when showing a SNAP, but as it does not make sense in this context, we opted for Community Sentiment and ad the endorsements instead. This works as expected. This can be closed.
