### ISSUE TITLE
AAU, I see a small introduction message when I connect to the directory

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#128]
As a User,
I see a small introduction message when I connect to the directory
So that ...

---

## Technical notes:

-
-

## Out of scope:

-
-

## Acceptance Criteria:

- [ ]  Given that I am in the discovery page, I see a frame with the description of the experimentation

## Definition of Ready

- [ ] Figma design ready
- [ ] Acceptance criteria ready
- [ ] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com)

**Comment by jvelasquez** [comment]
Text does not match what it is described in #132

**Comment by jvelasquez** [comment]
@alainncls , @satyajeetkolhapure  can you please lead me in this one?
