### ISSUE TITLE
AAU, I see the Snaps that have been developed by a user

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#130]
As a User,
I see the Snaps that have been developed by a user
So that I can make my opinion on this user and access their Snaps

---

## Technical notes:

- Fetch the `snaps-registry.json` file

## Out of scope:

- Indexing the snaps registry
- Pagination

## Acceptance Criteria:

- [x] Given that I access a profile of an user that has developed snaps (Builder), I see the list of the Snaps developed in the section "Developed by this User"
- [x] Given that I access a profile of an user that hasn't developed snaps, I don't see the section "Developed by this User"
- [x] Given that I click on a developed snap I access to the snap page

## Definition of Ready

- [x] Figma design ready
- [x] Acceptance criteria ready
- [x] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=3443%3A65728&mode=design&t=FaF0ch89ETKBlfYz-1)

Developed Snaps Section:
<img width="615" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0t2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64b599817ca1476a5e98675c2febdd4d57acc487/image.png" alt="image.png" />

Full page:
<img width="435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1N2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8d68ab45d20c0d022b71727b4af8a53431cb588/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
I can see more than "the last three snaps" developed by user, for example https://permissionless.snaps.metamask.io/dev/account/?address=0x4EBee6bA2771C19aDf9AF348985bCf06d3270d42 -- Is this working as expected? @alainncls @satyajeetkolhapure  ? Thanks

I can see no section when the user has not developed any, for example https://permissionless.snaps.metamask.io/dev/account/?address=0x7c0d681098a9d46bd34637870c3afa4bfc9ec720
