### ISSUE TITLE
AAU, I visualize and endorse a user technical expertise

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#142]
As a User,
I visualize and endorse a user technical expertise
So that I know more about them

---

## Technical notes:

- Move the endorse button to the "technical expertise" section of the profile
- Sort endorsements in reverse chronological order
- If the currently connected user has endorsed this user, display `you` first
- Display first 3 endorsements

## Out of scope:

- Endorsement mechanism is already working

## Acceptance Criteria:

- [ ] Given that I am in the user profile I can see all their technical expertises
- [ ] Given that I am in the user profile I can see the endorse button in the "technical expertises" section (endorse action is already implemented, we just move the button)
- [ ] Given that I am in the user profile  I see the top ranking user
- [ ] Given that I am in the user profile  I see "me" if I endorsed the user

## Definition of Ready

- [x] Figma design ready
- [ ] Acceptance criteria ready
- [ ] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=3443%3A65728&mode=design&t=FaF0ch89ETKBlfYz-1)

<img width="1273" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a47321526afd8c3a57f13ea6aa83bccf94e7fe09/image.png" alt="image.png" />

<img width="435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3l2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41bf917e4172340bc5fbb6f062c6cad99f9929c9/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
I can see "you" If I have endorsed the user, otherwise it can considered DONE. @alainncls @satyajeetkolhapure  

https://permissionless.snaps.metamask.io/dev/account/?address=0xc63cabe93bb29c61e337a87b2e3d4d7c5f5556c0

<img width="974" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2YwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed22689e4d296e33c7b0dfa30a6edbd547b0f7e0/image.png" alt="image.png" />
