### ISSUE TITLE
Harmonize Endorsement/Report Modals labels

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#150]
As a XXX,
I want to ...,
So that ...

---

## Technical notes:

- Account endorsement / report
- Snap endorsement / report

## Out of scope:

-
-

## Acceptance Criteria:

- [ ] Given that ... , when ..., then ...
- [ ] Given that ... , when ..., then ...

## Definition of Ready

- [ ] Figma design ready
- [ ] Acceptance criteria ready
- [ ] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com)

Snaps
<img width="362" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d137d4264e4282932e4ee76d78a07b59bbadfe1a/image.png" alt="image.png" />
<img width="373" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2JxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--493854fdd2c4ddebc36576cd8f1b73402cc9626b/image.png" alt="image.png" />

Accounts
<img width="363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ZxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84522a90bba183d0cec2173255ff612b37ac92b7/image.png" alt="image.png" />
<img width="364" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2pxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed05a3d30a55e38f659f3ce643d3cb059fb7e912/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
Validated, it can be considered DONE. @alainncls @satyajeetkolhapure   please move this one to DONE. 

https://permissionless.snaps.metamask.io/dev/account/?address=0x690fcde0b69b8b66342ac390a82092845c6f7f1c
