### ISSUE TITLE
AAU, I want to see the list of users who have endorsed a specific technical expertise

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#160]
As a User,
I want to see the list of users who have endorsed a specific technical expertise
So that I can understand who has contributed to the evaluation of that expertise

---

## Technical notes:

- Make the "`+ x more`" text clickable
- On click, display the modal
- Trust assertions with a level of 0 are considered as neutral (endorsements' levels need to be strictly > 0)

## Out of scope:

- User badges

## Acceptance Criteria:

- [ ] Given that I click on the link of the users that endorsed me regarding "software development", I see a modal with the list of these users
- [ ] Given that I click on the link of the users that endorsed me regarding "software security", I see a modal with the list of these users
- [ ] Given that I scroll down the list of users I see "10 more" button to load more users
- [ ] Given that I navigate to the technical expertise of an user profile I don't see endorsements with a level <= 0

## Definition of Ready

- [x] Figma design ready
- [x] Acceptance criteria ready
- [x] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=3724%3A42375&mode=design&t=7CwIXgxGa7e1BnO1-1)

<img width="435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHlTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3b944cc13fac6d5007b2950996cc3b1dd1f26ae/image.png" alt="image.png" />

**Comment by vivek-consensys** [comment]
@alainncls I do not see the modal of the endorsements. is this a bug or not valid?

<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVpQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f7e10243e083cfbf111a65e73314967e0002ba9/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
@vivek-consensys  
The modal is displayed when the list has to be broken and a +X more is displayed. So it is working as expected as can be seen in the following url.

https://permissionless.snaps.metamask.io/dev/account/?address=0x47170ceae335a9db7e96b72de630389669b33471

This can be closed.
