### ISSUE TITLE
AAU, I want to see the list of users who have endorsed or reported a Snap

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#161]
As a User,
I want to see the list of users who have endorsed or reported a Snap
So that I can understand from which users the community sentiment has been calculated

---

## Technical notes:

- Make the "x endorsements" text clickable
- Make the "x reports" text clickable
- On click, display the modal

## Out of scope:

- User badges

## Acceptance Criteria:

- [ ] Given that I am on the community sentiment modal and I click on the link of endorsing user, I see a modal with the list of these users, order by rank ASC
- [ ] Given that I am on the community sentiment modal and I click on the link of reporting user, I see a modal with the list of these users, order by rank ASC
- [ ] Given that I scroll down the list of users I see "10 more" button to load more users

## Definition of Ready

- [X] Figma design ready
- [x] Acceptance criteria ready
- [X] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=3724%3A42824&mode=design&t=NihowB3ulGyZXG6B-1)

<img width="435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dfdcfd11d5fcdf9151ac687041cf7188ddb8382/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
This can be seen in the following URL: https://permissionless.snaps.metamask.io/dev/snap/npm/solflare-wallet/solana-snap/ 

This is implemented and is working as expected.

<img width="1573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTVNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e8be8f637a5f76415e82b1db02c72f44fd5f99c/image.png" alt="image.png" />
