### ISSUE TITLE
AAU, I see the special user badges (builder and auditor badges)

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#164]
As a User
I see the special user badges
So that I can evaluate the trustworthiness of an user

---

## Technical notes:

Special user badges are inherent to the user, awarded for being part of an allowlist or for having developed Snaps.

- **Builder**: registered snap > 0
- **Auditor**: address part of the auditor list in the `snaps-registry.json`
- Color for these badges: green

## Out of scope:

-
-

## Acceptance Criteria:

- [ ] Given that I am in an user profile I see the `Builder ` badge, if it has developed at least one snap
- [ ] Given that I am in an user profile I see the `Auditor` badge, if it is a whitelisted auditor
- [ ] Given that I am in an user profile I see the user' badges (Builder, Auditor, Software Engineer, Security Engineer) below the user name

## Definition of Ready

- [ ] Figma design ready
- [x] Acceptance criteria ready
- [x] Technical grooming done

## Mockup design

No Figma.
The user badges should be below the name (instead of above)
Use the same look & feel that other badges, with the following emoticons:
- 🛡 Auditor
- 🛠 Builder

**Comment by satyajeetkolhapure** [comment]
🛡️ auditor

**Comment by jvelasquez** [comment]
I can see Builder in GREEN

https://permissionless.snaps.metamask.io/dev/account/?address=0xa1e08

<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGIwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--825ea272bb86fd138ca0528bba96522669e38ae2/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
I see the Auditor badge in ORANGE, this as expected? 

https://permissionless.snaps.metamask.io/dev/account/?address=0x9843D9bDb9a7cf7A5B0A18E1d1510A288e1F4A2D 

<img width="1256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHowQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d0d2688832eabde5407079f0fe657ef28322e89/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
Can you please have a look into this @alainncls  @satyajeetkolhapure ? Thanks

**Comment by vivek-consensys** [comment]
I do not see any of the auditor badges. @alainncls @satyajeetkolhapure

**Comment by jvelasquez** [comment]
This is a **BUG**
If we come from community page and go to auditor profile page, we will see the page, if we go directly to the auditor page we won't see the badge. Will need to be fixed. We will set it as Priority 2
