### ISSUE TITLE
Change user badges to "Security engineer" & "Software engineer"

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#179]
---

## Technical notes:

-
-

## Out of scope:

-
-

## Acceptance Criteria:

- [x] Given that I am accessing an user page that have been endorsed for "Security Engineer" expertise, I see the "Security Engineer" badge
- [x] Given that I am accessing an user page that have been endorsed for "Software Engineer" expertise, I see the "Software Engineer" badge

## Definition of Ready

- [ ] Figma design ready
- [x] Acceptance criteria ready
- [ ] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com)

**Comment by jvelasquez** [comment]
I can still see "Auditor" in a user profile. 

https://permissionless.snaps.metamask.io/dev/account/?address=0x381c5dd2c5f13d4d7d63f0c2318d58070a538c79 

<img width="1262" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEQwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cb1a6149a16ebd1cb793ec5074eb6a74862c07c/image.png" alt="image.png" />


Can you please check this one @alainncls , @satyajeetkolhapure  ? Thanks
