### ISSUE TITLE
[BUG] DID is displayed instead of ENS/address in "Developer" for a Snap

### ISSUE THREAD

**Issue by alainncls** [MetaMask/permissionless-snaps-directory#181]
Example: https://permissionless.snaps.metamask.io/snap/npm/ethereum-attestation-service/eas-metamask-snap/
<img width="137" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de7b3d877fbbe50b227b2608d3a69b233af1db49/image.png" alt="image.png" />

Here, we should see `eas.eth` instead of `did:...`.
Also, the link should be aligned below the 'Developer' label.

## Acceptance Criteria:
- [x] Given that I am in an Snaps profile, I see the developer ENS or address

**Comment by vivek-consensys** [comment]
Fixed 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04a0883e9efd2bc674ae3e18ac9e6f2bbc84ec1a/image.png" alt="image.png" />
