### ISSUE TITLE
[BUG] Add missing spaces

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#184]
---

## Technical notes:

-
-

## Out of scope:

-
-

## Definition of Ready

- [ ] Figma design ready
- [ ] Acceptance criteria ready
- [ ] Technical grooming done

## Mockup design

<img width="249" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGFRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d37aaff22c9326e3ae4122486740a0311233e22a/image.png" alt="image.png" />

<img width="185" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE9RQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09491cd7e6392c4ce44518bc4d604925110e16f2/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
I can see correct indentation, please move this to done @alainncls @satyajeetkolhapure  

https://permissionless.snaps.metamask.io/dev/snap/npm/consensys/starknet-snap/ 

<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEwwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--461837d3a06bf19c90f13d689c53f701849446b3/image.png" alt="image.png" />
