### ISSUE TITLE
AAU, I access the SPD survey

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#185]
As a User,
I access the SPD survey
So that I can share my feedback

---

## Technical notes:

- New Survey link: https://www.getfeedback.com/r/SugORXsV
-

## Out of scope:

-
-

## Acceptance Criteria:

- [ ] Given that I click on "Feedback" in the footer I access to the survey: https://www.getfeedback.com/r/SugORXsV

## Definition of Ready

- [x] Figma design ready
- [x] Acceptance criteria ready
- [x] Technical grooming done

## Mockup design

<img width="431" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekdSQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79c7544d99edc00555a268f68714cb01ba20bdee/image.png" alt="image.png" />

**Comment by jvelasquez** [comment]
I could access the survey as per indicated. Please move this to DONE @satyajeetkolhapure @alainncls 

Thanks.
