### ISSUE TITLE
AAU, I access an account profile

### ISSUE THREAD

**Issue by alainncls** [MetaMask/permissionless-snaps-directory#3]
As a user,
I want to access an account profile,
So that I can see the data linked to my account

----

## Technical notes:
* Accessed via `/account/?address=0x1234...abcd`
* Edit button visible only if it's the currently connected user's profile
* ENS resolution could be done through wagmi's [useEnsName hook](https://wagmi.sh/react/hooks/useEnsName)
* Add empty sections (`Developed Snaps`, `Security Reports`, `Trusted Circle`, `Reviews`)

## Out of scope:
* Lens and Farcaster name services resolution
* Access my profile (cf. #2)
* Content of sections (`Developed Snaps`, `Security Reports`, `Trusted Circle`, `Reviews`)

## Acceptance Criteria:
- [x] Given that I am accessing an account page (via direct entry of the URL or via navigation on the website), then I access the account profile
- [x] When I access an account profile, then I see all the empty sections ("Developed snaps", "Security Reports", "Ratings", "Trusted circle")
- [x] When I navigate to an account profile I see its account address
- [x] When I provide an invalid account address I get an error page

## Definition of Ready
- [X] Figma design ready
- [x] Acceptance criteria ready
- [X] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=1586%3A59913&mode=design&t=LOjPj9J00CsEAjPK-1)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2dHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62fae0af14a48d51480aee8e0ba7bcd0b32f1c06/profile-page.png)

**Comment by ChaimaKhiari** [comment]
Proceed with this address: 
`/account?address=0x123456`

**Comment by vivek-consensys** [comment]
Tested full acceptance criteria, see here: 
https://www.notion.so/metamask-consensys/04b33da3b17f42619427cddb7a806746?v=112946b65bc844b6a4a2bddd321488ea
