### ISSUE TITLE
AAU, I want to see the full activity of a user

### ISSUE THREAD

**Issue by ChaimaKhiari** [MetaMask/permissionless-snaps-directory#47]
As a User, 
I want to see the full activity of an account,
So that I can keep track of everything

---

## Technical notes:

- Query the last 10 assertions issued by the user

## Out of scope:
- Pagination
- Released Snaps
- Received endorsements/reports

## Acceptance Criteria:

- [ ] Given that I am on a user profile and scroll down to the "Activity" section, I see the last 10 assertions they have issued
- [ ] Given that I click on a Snap name, I access to its page
- [ ] Given that I click on a Peer address/ENS, I access to their profile

## Definition of Ready

- [x] Figma design ready
- [x] Acceptance criteria ready
- [X] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=3443%3A65728&mode=design&t=FaF0ch89ETKBlfYz-1)

<img width="1309" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2ZUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75086f5e0fa1ec544a01e0f3dff0089f4f98112f/image.png" alt="image.png" />

<img width="435" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0N2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a46750020d899e1b7dcad71603e989d7ec799342/image.png" alt="image.png" />

**Comment by eriknson** [comment]
- [x] [Design](https://www.figma.com/file/8N6pTs2HnDJvGQ1tVPTPox/Directory?type=design&node-id=3443%3A65728&mode=design&t=IVxWQ6fai48Vwt3M-1) now good to go

**Comment by jvelasquez** [comment]
All the acceptance criteria is met. @alainncls , @stanleyyconsensys can be moved to done.
