### ISSUE TITLE
AAU, I persist my issued trust assertions

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#59]
As a User,
I persist my issued trust assertions (account and snap),
So that my trust assertions can be verified and used to compute a trust score

----

## Technical notes:
* Create API POST `/assertions/{account/snap}` To store snap/account assertion in database with sequence ID
* Create API GET `/assertions/{subjectID}` To get the assertions linked to a subject
* Create API GET `/assertions` To get assertions in sequence order, and allow consumer to conditional query the API with "from" sequence ID , and "to" sequence ID , "to" is optional, without "to", automatically fetch the latest  

## Out of scope:
* UI to issue attestations (cf. [#5](https://app.zenhub.com/workspaces/snaps-permissionless-distribution-652446543fea3f1af2ecafbf/issues/gh/metamask/permissionless-snaps-directory/5), [#6](https://app.zenhub.com/workspaces/snaps-permissionless-distribution-652446543fea3f1af2ecafbf/issues/gh/metamask/permissionless-snaps-directory/6) & [#7](https://app.zenhub.com/workspaces/snaps-permissionless-distribution-652446543fea3f1af2ecafbf/issues/gh/metamask/permissionless-snaps-directory/7))
* Attestations reading

## Acceptance Criteria:
- [ ] Given that I authenticate in the Snaps Directory and I navigate to an account profile, and that I endorse a given account, I have my assertion stored in the database
- [ ] Given that I endorsed the account, I see a disabled button "endorsed" (instead of the "endorse" button)
- [ ] Given that I authenticate in the Snaps Directory and I navigate to an account profile, and that I report a given account, I have my assertion stored in the database
- [ ] Given that I reported the account, I see a disabled button "reported" (instead of the "report" button)
- [ ] Given that I authenticate in the Snaps Directory and I navigate to a snap profile, and that I endorser a given snap version, I have my assertion stored in the database 
- [ ] Given that I endorsed, I see a disabled button "endorsed" (instead of the "endorse" button)
- [ ] Given that I authenticate in the Snaps Directory and I navigate to a snap profile, and that I report a given snap version, I have my assertion stored in the database 
- [ ] Given that I reported, I see a disabled button "reported" (instead of the "report" button)

## Definition of Ready
- [x] Acceptance criteria ready
- [X] Technical grooming done

## Mockup design

N/A

**Comment by ChaimaKhiari** [comment]
@stanleyyconsensys @satyajeetkolhapure  will simoultaniously work on it
One on write
One on read

**Comment by alainncls** [comment]
[PR](https://github.com/MetaMask/permissionless-reputation-indexer/pull/16) for the backend/API is merged :white_check_mark:

**Comment by alainncls** [comment]
Creation of assertion is merged ✅ and delivered on the [dev env.](https://metamask.github.io/permissionless-snaps-directory/dev/) ✅

**Comment by A-Feder** [comment]
QA test ✅
