### ISSUE TITLE
Reception of trust scores from the trust computer

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#63]
As a User,
I see any user's account badges depending on their global trust scores
So that end-users can see my reputation according to the MetaMask pre-set trust graph

----

## Technical notes:

* Create the "write" endpoint handling "TrustScore" at the API level:
   * For K3L to provide the payload containing the updated trust scores (every 10 minutes)
   * `POST /global-trust-scores  {<trustScoresDocuments>}`
   * When receiving an update of trust scores:
      * Replace the score for each pre-existing DID
      * Add the new DID <> Score mappings

## Out of scope:

* Compute the score and upload the result to our API (done by Karma3 Lab)

## Acceptance Criteria:

- [ ] Given that I provide assertions to the Trust Computer, the Trust computer is able to provide the computed trust scores every 10 minutes

## Definition of Ready
- [X] Acceptance criteria ready
- [X] Technical grooming done

## Mockup design

N/A

**Comment by ChaimaKhiari** [comment]
Message queue system (to be investigated) @stanleyyconsensys  @mario-christopher to be investigated

**Comment by alainncls** [comment]
```
// TODO: remove hardcode bucket and key
```

**Comment by stanleyyconsensys** [comment]
It look likes k3l is zipping everything in a zip file, we have to unzip it
