### ISSUE TITLE
AAU, I see the addresses of developers and auditors

### ISSUE THREAD

**Issue by dayksx** [MetaMask/permissionless-snaps-directory#84]
As a user,
I want to see the addresses of developers and auditors
So that I can endorse or report them, ad well as see their reputation

---

## Technical notes:

- Fetch `address` field in the copied snaps registry https://github.com/MetaMask/permissionless-snaps-directory/blob/dev/snaps-registry.json

 ```json
"audits": [
          {
            "auditor": "Sayfer",
            "report": "https://sayfer.io/audits/metamask-snap-audit-report-for-aleo/",
             "address": "0x44dc4E3309B80eF7aBf41C7D0a68F0337a88F044"
}
```
 ```json
"author": {
          "name": "ChainSafe",
          "website": "https://chainsafe.io/",
          "address": "0x44dc4E3309B80eF7aBf41C7D0a68F0337a88F044"
}
```

## Out of scope:

-
-

## Acceptance Criteria:

- [ ] Given that I am in a snap profile, I can see the "developer" information with its address / ens linking to its user profile, under the label "developer"
- [ ] Given that I am in a snap profile and click on see more, I can see the snaps' auditor information with its address / ens linking to its user profile under the label "auditor"
- [ ] Given that I am in a snap profile, I see the associated website url under the label "website"

## Definition of Ready

- [ ] Figma design ready
- [x] Acceptance criteria ready
- [x] Technical grooming done

## Mockup design

=> [FIGMA](https://www.figma.com)

<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzdUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e786890730468fb22af2dc9a3bb00c78508b281c/image.png" alt="image.png" />

**Comment by eriknson** [comment]
- Let's drop the external link icon for the profile level `developer` field as we start linking to (onchain) profiles from it
- Let's introduce the `audited by` and `audit reports` fields

<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2krQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31f193661e3d9e3cf3f0f0d06b0ac4cf0188d37c/Screenshot%202024-03-07%20at%2010.14.48.png" alt="Screenshot 2024-03-07 at 10.14.48.png" />

**Comment by jvelasquez** [comment]
I can celary see the Audited By field in the when I click on "see details", and also the audit Reports. 

When no auditor address is present, I do not see the Audited By field, I assume this is working as expected.

```json
[
  {
    "auditor": "Cure53",
    "report": "https://cure53.de/pentest-report_silencelabs-snap.pdf"
  },
  {
    "auditor": "Cure53",
    "report": "https://cure53.de/audit-report_silencelabs-ecdsa-lib.pdf"
  },
  {
    "auditor": "Cure53",
    "report": "https://cure53.de/pentest-report_silencelabs-apps.pdf"
  }
]
```

@alainncls , @satyajeetkolhapure this can be moved to DONE.
